--- #YAML:1.0
name:               VMware-API-LabManager
version:            2.07
abstract:           VMware's Lab Manager public and private API
author:
    - Phil Pollard <bennie@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Data::Dumper:  0
    Net::SSL:      0
    perl:          5.006
    SOAP::Lite:    0.71
resources:
    bugtracker:
        web:  https://rt.cpan.org/Dist/Display.html?Name=VMware-API-LabManager
    repository:
        type:  git
        url:   git://github.com/bennie/perl-VMware-API-LabManager.git
        web:   http://github.com/bennie/perl-VMware-API-LabManager
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
