--- #YAML:1.0
name:               VMware-API-LabManager
version:            2.05
abstract:           VMware's Lab Manager public and private API
author:
    - Phil Pollard <bennie@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:               5.008001
    Data::Dumper:       0
    SOAP::Lite:         0.71
    Net::SSL:           0
resources:
    bugtracker:
        web:  https://rt.cpan.org/Dist/Display.html?Name=VMware-API-LabManager
    repository:
        type:  git
        url:   git://github.com/bennie/perl-VMware-API-LabManager.git
        web:   http://github.com/bennie/perl-VMware-API-LabManager
no_index:
    directory:
        - t
        - inc
provides:
    Rcs::Parser:
        file: lib/VMware/API/LabManager.pm
        version: 2.05
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
--- #YAML:1.0
name:               Rcs-Parser
version:            2.05
abstract:           Parse and analyze RCS files
author:
    - Phil Pollard <bennie@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:               5.008001
    Sort::Versions:     0
    Test::Simple:       0
resources:
    bugtracker:
        web:  https://rt.cpan.org/Dist/Display.html?Name=Rcs-Parser
    repository:
        type:  git
        url:   git://github.com/bennie/perl-Rcs-Parser.git
        web:   http://github.com/bennie/perl-Rcs-Parser
no_index:
    directory:
        - t
        - inc
provides:
    Rcs::Parser:
        file: lib/Rcs/Parser.pm
        version: 2.05
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
